"""What a derived image says about whose it is.

gallery.cfg `credit`, written as EXIF Artist/Copyright into every thumbnail,
preview and converted full, and when that value last changed -- so a
derivative written under the old one counts as stale and is rebuilt.

Its own module because the scanner needs it, and the scanner must not import
the web layer to get it. (It used to be handed a pair of callbacks by main.py
at import time instead.)
"""

from __future__ import annotations

import json
import logging
import os

from . import cfgio, config
from .runtime import settings

log = logging.getLogger("aperture.marks")

# ----- credit on the derived images (gallery.cfg owns it) ---------------
# Every thumbnail, preview and converted full is generated by scanner.py and
# carries an EXIF block written there: the `Software` tag naming this
# software (aperture/brand.py, not configurable), and — when gallery.cfg sets one
# — Artist/Copyright naming the operator:
#
#   credit = lucya      who took the photographs
#
# Metadata only: nothing is drawn onto a photograph, and the files under
# photos/ are never rewritten. The two names answer different questions and
# neither stands in for the other — the software says what made the file,
# the credit says whose picture it is.
#
# Changing `credit` re-derives what it affects on the next request, through
# the fingerprint below. Unrelated edits to gallery.cfg do not.
MARKS_STATE_FILE = "credit.state"


def credit() -> str | None:
    """gallery.cfg `credit`, or None. Read per request like every other cfg
    value here; scanner calls this for each derivative it writes."""
    return cfgio.joined(config.gallery_config(), "credit") or None


def stamp() -> float:
    """When `credit` last CHANGED, as an mtime scanner can compare a
    derivative against.

    Using gallery.cfg's own mtime would have been simpler and wrong: every
    unrelated edit to it — a welcome image, an album order — would then
    invalidate all ~800 thumbnails at once. So the resolved value is
    fingerprinted into a file under DATA_DIR and only a real change to it
    rewrites that file.

    The first run has nothing to invalidate — there is no earlier setting the
    files on disk could have been built under — so the record is created
    backdated to the epoch. Only changes made after that count."""
    path = settings.data_dir / MARKS_STATE_FILE
    fingerprint = json.dumps({"credit": credit()}, sort_keys=True)
    try:
        previous = path.read_text(encoding="utf-8")
    except OSError:
        previous = None
    if previous != fingerprint:
        try:
            # Written through a temp file: a full scan asks about this once
            # per derivative and a page render once per thumbnail, so several
            # threads can arrive at the same moment. A reader catching a
            # half-written file would see a mismatch and rebuild for nothing.
            tmp = path.with_suffix(".tmp")
            tmp.write_text(fingerprint, encoding="utf-8")
            os.replace(tmp, path)
            if previous is None:
                os.utime(path, (0, 0))
        except OSError as e:
            log.warning("could not record credit state: %s", e)
            return 0.0
    try:
        return path.stat().st_mtime
    except OSError:
        return 0.0
